u2v22/airpet

Gemfile
Gemfile.lock
app/views/layouts/application.html.erb
config/environments/development.rb
config/initializers/devise.rb
config/locales/devise.en.yml
config/routes.rb

created a generic email airpet. didn't create models yet.

added devise gem and setup config files

---

app/models/animal.rb
app/models/booking.rb
app/models/user.rb
config/routes.rb
db/migrate/20191202163631_devise_create_users.rb
db/migrate/20191202163931_create_animals.rb
db/migrate/20191202164027_create_bookings.rb
db/schema.rb
test/models/animal_test.rb
test/models/booking_test.rb
test/models/user_test.rb

I have created the models according to the schema.
I created the database and migrated it.
Also, changed the route to pages#home

Creating models

---

app/controllers/animals_controller.rb
app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
app/models/animal.rb
app/models/booking.rb
app/models/user.rb
app/views/devise/confirmations/new.html.erb
app/views/devise/mailer/confirmation_instructions.html.erb
app/views/devise/mailer/email_changed.html.erb
app/views/devise/mailer/password_change.html.erb
app/views/devise/mailer/reset_password_instructions.html.erb
app/views/devise/mailer/unlock_instructions.html.erb
app/views/devise/passwords/edit.html.erb
app/views/devise/passwords/new.html.erb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
app/views/devise/sessions/new.html.erb
app/views/devise/shared/_error_messages.html.erb
app/views/devise/shared/_links.html.erb
app/views/devise/unlocks/new.html.erb
config/routes.rb
test/controllers/animals_controller_test.rb
test/controllers/bookings_controller_test.rb
test/controllers/users_controller_test.rb

Added validations to the models

validations added in the models

---

app/views/pages/home.html.erb

couldn't create from as it needed dependencies from controllers.

feature: template for landing page

---

app/controllers/bookings_controller.rb

template for bookings

---

app/assets/stylesheets/components/_card.scss
app/assets/stylesheets/components/_index.scss
app/assets/stylesheets/pages/_animals.scss
app/views/animals/index.html.erb

I have made the grid for the index for the animal page. I have made it into 5 cards in every row like shown in figma.

Feature: I have finished the grid and the index of the animals page.

---

app/views/pages/home.html.erb

Feature: Ended up using just basic html form. No css styling yet.

Simple form landing

---

app/assets/stylesheets/components/_banner.scss
app/assets/stylesheets/components/_index.scss
app/controllers/animals_controller.rb
app/views/animals/show.html.erb
app/views/components/_banner.html.erb
db/seeds.rb

Adding animal show

---

app/views/layouts/application.html.erb

it shouldn't have been there in the first place

FIX remove container css from application.html.erb

---

app/views/components/_navbar.html.erb
app/views/devise/sessions/new.html.erb

feature: created route to sign in and added container for sign in

---

.gitignore
Gemfile
Gemfile.lock
app/assets/stylesheets/pages/_animals.scss
app/controllers/animals_controller.rb
app/models/animal.rb
app/uploaders/photo_uploader.rb
app/views/animals/new.html.erb
app/views/layouts/application.html.erb
db/migrate/20191202163931_create_animals.rb
db/migrate/20191203131428_add_photo_to_animals.rb
db/schema.rb

I have finished the view and the action New. The Create part we still need a User show for me to create a link to the pet after it has been created.

Creating new action for animals controller

---

app/views/animals/new.html.erb

I added the container to the New form

added container to the new view

---

app/views/layouts/application.html.erb
app/views/shared/_shared.html.erb

FIX moved flashes to shared folder and removed from application

---

app/controllers/animals_controller.rb
app/views/animals/new.html.erb
db/migrate/20191204102557_add_availability_to_animals.rb
db/schema.rb

Added the availability_start and end attribute to the animal model.
Changed code where the old attribute (availability) was used.

AnimalModel:Added the availability_start and end attribute

---

app/views/layouts/application.html.erb

Feature updated title

---

app/controllers/registrations_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.erb
app/views/devise/registrations/new.html.erb
config/routes.rb
db/migrate/20191204112304_add_extra_fieldsfor_user.rb
db/schema.rb
test/controllers/registrations_controller_test.rb

Feature: added first_name to the user sign in and edit  page

---

app/controllers/bookings_controller.rb
app/controllers/users_controller.rb
app/views/users/_animals.html.erb
app/views/users/_bookings.html.erb
app/views/users/show.html.erb

Added the show of the bookings in the User profile

Feature: added the display for the bookings in the user profile"

---

app/controllers/bookings_controller.rb
app/views/users/_animals.html.erb
app/views/users/_bookings.html.erb
db/seeds.rb

Added the delete part for the bookings inside the user profile

Delete bookings feature

---

Gemfile.lock
db/seeds.rb

little change to seeds

---

app/controllers/animals_controller.rb
app/javascript/plugins/init_mapbox.js

User can zoom in/out on map and the index cards will filter by what's in the bounding box of the map.

FEATURE Bookings map zoom

---

app/assets/stylesheets/pages/_animal_index.scss
app/assets/stylesheets/pages/_animals.scss
app/assets/stylesheets/pages/_index.scss
app/views/animals/index.html.erb

redid the html of the animal index page. Made an entire scss page just for it. lined up map with the animal cards. added a hover border on the card

animal index page layout and styling done

---

app/assets/stylesheets/pages/_animals.scss
app/views/animals/_form.html.erb

put your new pet up page is done

rent your pet page finished

---

app/views/pages/home.html.erb

landing page spacing is now fixed

landing page form is spaced better

---

app/controllers/animals_controller.rb

commented out bug
